<?php
/**
 * ShopEx licence
 *
 * @copyright  Copyright (c) 2005-2010 ShopEx Technologies Inc. (http://www.shopex.cn)
 * @license  http://ecos.shopex.cn/ ShopEx License
 */
// CREATE TABLE IF NOT EXISTS `topic`(
//     `topic_id` int UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL "自增id",
//     `topic_name` varchar(200) NOT NULL DEFAULT "" COMMENT "话题名称",
//     `topic_desc` varchar(400) NOT NULL DEFAULT "" COMMENT "话题描述",
//     `topic_start_time` int UNSIGNED NOT NULL DEFAULT 0 COMMENT "话题开始时间",
//     `topic_end_time` int UNSIGNED NOT NULL DEFAULT 0 COMMENT "话题结束时间",
//     `topic_img` varchar(400) NOT NULL DEFAULT "" COMMENT "话题图片",
//     `topic_color` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT "话题颜色0:白色 1:黑色",
//     `is_forbid` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT "话题禁言",
//     `create_time` int NOT NULL DEFAULT 0 COMMENT "创建时间",
//     `update_time` int NOT NULL DEFAULT 0 COMMENT "更新时间",
//     `flag` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT "状态：0正常；1删除"
// )ENGINE=InnoDB DEFAULT CHARSET=utf8;
return array(
    'columns' => array(
        'topic_id' =>array(
            'type' => 'integer',
            'required' => true,
            'comment'=> '自增id',
            'autoIncrement' => true,
            'length'=>11,
            // 'test'=>true
        ),
         'topic_ids' =>array(
            'type' => 'integer',
            'required' => true,
            'comment'=> '自增id',
            // 'autoIncrement' => true,
        ),
        'topic_name' =>array(
            'type' => 'text',
            'searchtype' => 'has',
            // 'length' => 200,
            'filtertype' => 'normal',
            'filterdefault' => 'true',
            'required' => true,
        ),
        'topic_desc' =>array(
            'type' => 'string',
            'length' => 200,
            'filterdefault' => 'true',
            'required' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 3,
            'label' => '话题描述',
            'comment'=> '话题描述',
        ),
        'topic_start_time' => array(
            'type' => 'time',
            'default' => 0,
            'required' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filterdefault' => true,
            'order' => 4,
            'label' => '话题开始时间',
            'comment' => '话题开始时间',
        ),
        'topic_end_time' => array(
            'type' =>'time',
            'default' => 0,
            'required' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filterdefault' => true,
            'order' => 5,
            'label' => '话题结束时间',
            'comment' => '话题结束时间',
        ),
        'topic_img' => array(
            'type' => 'string',
            // 'searchtype' => 'has',
            'length' => 400,
            'width' => 40,
            'filterdefault' => 'true',
            'required' => true,
            'label' => '话题图片',
            'order'=>6,
            'comment'=> '话题图片',
        ),
        'topic_color' => array(
            'type' => 'boolean',
            'default' => 0,
            'in_list' => true,
            // 'default_in_list' => true,
            'label' => '话题颜色',
            'comment' => '话题颜色0:白色 1:黑色',
            'editable' => true,
            'width' => 40,
            'order'=>7,
        ),
        'is_forbid' => array(
            'type' => 'boolean',
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'label' => '话题禁言',
            'comment' => '话题禁言 0：不禁言；1：禁言',
            'editable' => true,
            'width' => 40,
            'order'=>8,
        ),
        'is_hide' => array(
            'type' => 'boolean',
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'label' => '是否列表隐藏',
            'comment' => '是否列表隐藏 0：展示；1隐藏',
            'editable' => true,
            'width' => 40,
            'order'=>9,
        ),
        'create_time' => array(
            'type' => 'time',
            'comment' => '发布时间（无需精确到秒）',
            'editable' => true,
            'width' => 130,
            'order'=>10,
            'default' => 0,
        ),
        'update_time' =>array(
            'type' => 'time',
            'comment' => '更新时间（精确到秒）',
            'label' => '更新时间',
            'editable' => false,
            'width' => 130,
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'order'=>11,
        ),
        'flag' => array(
            'type' => 'boolean',
            'default' => 0,
            'default_in_list' => true,
            'comment' => '当前状态：0：正常；1：删除',
            'editable' => true,
            'width' => 40,
            'order'=>12,
            'default_in_list' => true,
            'label' => '当前状态',
        ),
    ),
    // 'primary' => 'topic_id',:
    'comment' => '话题表',
    'index' => array(
        'ind_cat_path' => ['columns' => ['flag']],
        'ind_cat_name' => ['columns' => ['update_time']],
        'ind_modified_time' => ['columns' => ['create_time','update_time']],
        'ind_ordersort' => ['columns' => ['is_hide']],
    )
);